package vocabulary

import (
	"fmt"
	"strings"
	"testing"
)

// names renders declarations as name@line for compact comparison.
func names(values []Declaration) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, fmt.Sprintf("%s@%d", value.Name, value.Line))
	}
	return strings.Join(parts, " ")
}

func check(t *testing.T, path, source, want string) []Declaration {
	t.Helper()
	got := Detect(path, []byte(source))
	if names(got) != want {
		t.Errorf("%s: got %q, want %q", path, names(got), want)
	}
	return got
}

func TestGoReportsOnlyConstantsOfANamedDomainType(t *testing.T) {
	got := check(t, "kinds.go", `package assessment

// enum Kind { NotThis } lives in a comment.
type Kind string

const (
	KindTesttaker Kind = "testtaker"
	KindProctor   Kind = "proctor" // a trailing comment, with a comma
	_             Kind = "skipped"
)

type Level int

const (
	LevelLow Level = iota
	LevelMid
	LevelHigh
)

const (
	maxRetries     = 3
	defaultTimeout time.Duration = 5 * time.Second
	bufferSize     int = 1 << 10
	greeting           = "a, b = c"
	followsUntyped
)

const Single Kind = "single"
const plain = 1
`, "KindTesttaker@7 KindProctor@8 LevelLow@15 LevelMid@16 LevelHigh@17 Single@28")
	if got[0].Kind != TypedConstant || got[0].Container != "Kind" || got[0].Language != "go" {
		t.Fatalf("declaration = %#v", got[0])
	}
	check(t, "kinds_test.go", "package a\n\nconst (\n\tA Kind = 1\n)\n", "")
	check(t, "zz.pb.go", "package a\n\nconst (\n\tA Kind = 1\n)\n", "")
	check(t, "gen.go", "// Code generated by x. DO NOT EDIT.\npackage a\n\nconst A Kind = 1\n", "")
}

func TestTypeScriptEnumsButNotConstants(t *testing.T) {
	check(t, "status.ts", `// enum Fake { Nope }
export const MAX_SITTINGS = 3;
const label = "enum Nope { X }";
export enum SittingStatus {
  Scheduled = 'scheduled',
  InProgress = "in, progress",
  Completed,
}
const enum Mode { Timed = 1, Untimed }
declare enum Empty {}
`, "Scheduled@5 InProgress@6 Completed@7 Timed@9 Untimed@9")
}

func TestJavaEnumConstantsStopAtTheirSemicolon(t *testing.T) {
	check(t, "Role.java", `package x;

public enum Role implements Named {
    @Deprecated
    TESTTAKER("testtaker", 1),
    PROCTOR("proctor", 2) {
        @Override public String label() { return "p"; }
    };

    private final String code;
    Role(String code, int order) { this.code = code; }
    public String code() { return code; }
}
`, "TESTTAKER@5 PROCTOR@6")
}

func TestKotlinCSharpRustAndSwiftEnums(t *testing.T) {
	check(t, "Role.kt", `enum class Role(val code: String) {
    TESTTAKER("t"),
    PROCTOR("p");

    fun label() = code
}
`, "TESTTAKER@2 PROCTOR@3")
	check(t, "Role.cs", `public enum Role : byte
{
    [Description("taker")] Testtaker = 1,
    Proctor,
}
`, "Testtaker@3 Proctor@4")
	check(t, "role.rs", `fn longest<'a>(x: &'a str) -> &'a str { x }

#[derive(Debug)]
pub enum Role {
    #[default]
    Testtaker,
    Proctor(u32),
    Grader { id: u64, name: String },
}
const LIMIT: usize = 3;
`, "Testtaker@6 Proctor@7 Grader@8")
	check(t, "Role.swift", `enum Role: String, Codable {
    case testtaker, proctor = "p"
    indirect case nested(Role)
    var label: String {
        switch self {
        case .testtaker: return "t"
        default: return "x"
        }
    }
}
`, "testtaker@2 proctor@2 nested@3")
}

func TestPythonEnumClassesOnly(t *testing.T) {
	check(t, "roles.py", `from enum import Enum, IntEnum
import enum

MAX_SITTINGS = 3

class Settings:
    TIMEOUT = 5

class Role(Enum):
    """Who takes part.

    NOT_A_MEMBER = 1
    """
    TESTTAKER = "testtaker"
    PROCTOR = "proctor"
    _ignore_ = ["x"]

    def label(self):
        LOCAL = 1
        return self.value

class Level(enum.IntEnum):
    LOW: int = 1
    HIGH = 2
    # COMMENTED = 3

def after():
    pass
`, "TESTTAKER@14 PROCTOR@15 LOW@23 HIGH@24")
}

func TestUnsupportedFilesAndRegistration(t *testing.T) {
	check(t, "README.md", "enum X { A }", "")
	if Supported("a.md") || !Supported("a.GO") {
		t.Fatal("support is by extension, case-insensitively")
	}
	Register(fixed{}, ".vocab")
	defer delete(detectors, ".vocab")
	check(t, "a.vocab", "", "Word@1")
}

type fixed struct{}

func (fixed) Language() string { return "fixed" }
func (fixed) Declarations([]byte) []Declaration {
	return []Declaration{{Name: "Word", Line: 1, Kind: EnumMember, Language: "fixed"}}
}

// A suggested term is the domain word, not the Go identifier: the words the
// member shares with its type are the type's, not the term's.
func TestHumanizeSuggestsTheDomainWord(t *testing.T) {
	for _, test := range []struct{ name, container, want string }{
		{"ResolutionExcluded", "Resolution", "excluded"},
		{"StateCoveredDirect", "AxisState", "covered direct"},
		{"UnitChangedLine", "Unit", "changed line"},
		{"TEST_TAKER", "Role", "test taker"},
		{"HTTPServer", "", "http server"},
		{"Unit", "Unit", "unit"},
		{"reviewer-kind", "", "reviewer kind"},
	} {
		if got := Humanize(test.name, test.container); got != test.want {
			t.Errorf("Humanize(%q, %q) = %q, want %q", test.name, test.container, got, test.want)
		}
	}
}
