package theme

// tokens is the design-token contract, in the order CSS emits it. The app
// stylesheet, generated slides, and a user theme all speak these names.
var tokens = []Token{
	{Name: "bg", Group: "surface", Kind: "color", Light: `#ffffff`, Dark: `#0d1117`},
	{Name: "bg-subtle", Group: "surface", Kind: "color", Light: `#f6f8fa`, Dark: `#161b22`},
	{Name: "bg-inset", Group: "surface", Kind: "color", Light: `#eef1f4`, Dark: `#1c2128`},
	{Name: "ink", Group: "surface", Kind: "color", Light: `#1f2328`, Dark: `#e6edf3`},
	{Name: "muted", Group: "surface", Kind: "color", Light: `#59636e`, Dark: `#9198a1`},
	{Name: "faint", Group: "surface", Kind: "color", Light: `#59636e`, Dark: `#8b949e`},
	{Name: "line", Group: "surface", Kind: "color", Light: `#d1d9e0`, Dark: `#30363d`},
	{Name: "line-soft", Group: "surface", Kind: "color", Light: `#e7ebef`, Dark: `#21262d`},
	{Name: "accent", Group: "status", Kind: "color", Light: `#0969da`, Dark: `#4493f8`},
	{Name: "accent-soft", Group: "status", Kind: "color", Light: `#ddf4ff`, Dark: `#121d2f`},
	{Name: "accent-line", Group: "status", Kind: "color", Light: `#54aeff`, Dark: `#316dca`},
	{Name: "green", Group: "status", Kind: "color", Light: `#116329`, Dark: `#3fb950`},
	{Name: "red", Group: "status", Kind: "color", Light: `#a40e26`, Dark: `#f85149`},
	{Name: "amber", Group: "status", Kind: "color", Light: `#9a6700`, Dark: `#d29922`},
	{Name: "sel", Group: "surface", Kind: "color", Light: `#eaf3fe`, Dark: `#132132`},
	{Name: "add-bg", Group: "diff", Kind: "color", Light: `#e6ffec`, Dark: `#12261e`},
	{Name: "add-line", Group: "diff", Kind: "color", Light: `#2da44e`, Dark: `#3fb950`},
	{Name: "del-bg", Group: "diff", Kind: "color", Light: `#ffebe9`, Dark: `#25171c`},
	{Name: "del-line", Group: "diff", Kind: "color", Light: `#cf222e`, Dark: `#f85149`},
	{Name: "code-bg", Group: "diff", Kind: "color", Light: `#ffffff`, Dark: `#0d1117`},
	{Name: "code-gutter", Group: "diff", Kind: "color", Light: `#f6f8fa`, Dark: `#161b22`},
	{Name: "warning-bg", Group: "status", Kind: "color", Light: `#fff8e6`, Dark: `#2d240c`},
	{Name: "warning-line", Group: "status", Kind: "color", Light: `#e0c98a`, Dark: `#9e6a03`},
	{Name: "danger-bg", Group: "status", Kind: "color", Light: `#fff5f4`, Dark: `#25171c`},
	{Name: "danger-line", Group: "status", Kind: "color", Light: `#e5b3ae`, Dark: `#f85149`},
	{Name: "frosted-bg", Group: "chrome", Kind: "color", Light: `#ffffffed`, Dark: `#0d1117ed`},
	{Name: "toolbar-bg", Group: "chrome", Kind: "color", Light: `#ffffffee`, Dark: `#0d1117ee`},
	{Name: "accent-hover-bg", Group: "chrome", Kind: "color", Light: `#cfeaff`, Dark: `#1c2d41`},
	{Name: "accent-hover-ink", Group: "chrome", Kind: "color", Light: `#0550ae`, Dark: `#79c0ff`},
	{Name: "landmark-bg", Group: "chrome", Kind: "color", Light: `#f5f9ff`, Dark: `#1c2733`},
	{Name: "footnote-hover-bg", Group: "chrome", Kind: "color", Light: `#dbeafe`, Dark: `#1c2d41`},
	{Name: "citation-bg", Group: "chrome", Kind: "color", Light: `#e8f2ff`, Dark: `#121d2f`},
	{Name: "landmark-affordance-bg", Group: "chrome", Kind: "color", Light: `#fffffff2`, Dark: `#161b22f2`},
	{Name: "button-hover", Group: "chrome", Kind: "color", Light: `#e2e6ea`, Dark: `#30363d`},
	{Name: "primary-bg", Group: "status", Kind: "color", Light: `#0969da`, Dark: `#1f6feb`},
	{Name: "primary-hover", Group: "status", Kind: "color", Light: `#0860c4`, Dark: `#1158c7`},
	{Name: "primary-ink", Group: "status", Kind: "color", Light: `#fff`, Dark: `#fff`},
	{Name: "active-fragment-line", Group: "chrome", Kind: "color", Light: `#c8e1ff`, Dark: `#316dca`},
	{Name: "add-gutter", Group: "diff", Kind: "color", Light: `#d9f6e0`, Dark: `#142c22`},
	{Name: "del-gutter", Group: "diff", Kind: "color", Light: `#ffdcd8`, Dark: `#321c22`},
	{Name: "copied-bg", Group: "chrome", Kind: "color", Light: `#1f2328`, Dark: `#30363d`},
	{Name: "copied-ink", Group: "chrome", Kind: "color", Light: `#fff`, Dark: `#e6edf3`},
	{Name: "syntax-keyword", Group: "syntax", Kind: "color", Light: `#cf222e`, Dark: `#ff7b72`},
	{Name: "syntax-string", Group: "syntax", Kind: "color", Light: `#0a3069`, Dark: `#a5d6ff`},
	{Name: "syntax-number", Group: "syntax", Kind: "color", Light: `#0550ae`, Dark: `#79c0ff`},
	{Name: "syntax-comment", Group: "syntax", Kind: "color", Light: `#6e7781`, Dark: `#8b949e`},
	{Name: "syntax-type", Group: "syntax", Kind: "color", Light: `#953800`, Dark: `#ffa657`},
	{Name: "syntax-property", Group: "syntax", Kind: "color", Light: `#8250df`, Dark: `#d2a8ff`},
	{Name: "syntax-punctuation", Group: "syntax", Kind: "color", Light: `#57606a`, Dark: `#c9d1d9`},
	{Name: "ui", Group: "shape", Kind: "font", Light: `-apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,"Helvetica Neue",Arial,sans-serif`, Dark: ``},
	{Name: "mono", Group: "shape", Kind: "font", Light: `ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,"Liberation Mono",monospace`, Dark: ``},
	{Name: "top", Group: "shape", Kind: "length", Light: `44px`, Dark: ``},
	{Name: "shadow", Group: "shape", Kind: "shadow", Light: `0 6px 24px #1f232814,0 1px 3px #1f23281f`, Dark: `0 6px 24px #01040966,0 1px 3px #010409aa`},
	{Name: "radius", Group: "shape", Kind: "length", Light: `6px`, Dark: ``},
	{Name: "diagram-canvas", Group: "diagram", Kind: "color", Light: "#fafaf8", Dark: "#0d1117", Doc: "Slide canvas behind a generated diagram."},
	{Name: "diagram-normal-fill", Group: "diagram", Kind: "color", Light: "#ffffff", Dark: "#161b22", Doc: "Fill of the normal style."},
	{Name: "diagram-normal-stroke", Group: "diagram", Kind: "color", Light: "#64748b", Dark: "#6e7681", Doc: "Stroke of the normal style."},
	{Name: "diagram-normal-ink", Group: "diagram", Kind: "color", Light: "#172033", Dark: "#e6edf3", Doc: "Text of the normal style."},
	{Name: "diagram-primary-fill", Group: "diagram", Kind: "color", Light: "#edf5ff", Dark: "#0c2d6b", Doc: "Fill of the primary style."},
	{Name: "diagram-primary-stroke", Group: "diagram", Kind: "color", Light: "#2563eb", Dark: "#4493f8", Doc: "Stroke of the primary and emphasis styles."},
	{Name: "diagram-primary-ink", Group: "diagram", Kind: "color", Light: "#153869", Dark: "#cae8ff", Doc: "Text of the primary and emphasis styles."},
	{Name: "diagram-secondary-stroke", Group: "diagram", Kind: "color", Light: "#94a3b8", Dark: "#6e7681", Doc: "Stroke of the secondary style."},
	{Name: "diagram-secondary-ink", Group: "diagram", Kind: "color", Light: "#526174", Dark: "#9198a1", Doc: "Text of the secondary, boundary, and caption styles."},
	{Name: "diagram-warning-fill", Group: "diagram", Kind: "color", Light: "#fff7e6", Dark: "#2d240c", Doc: "Fill of the warning style."},
	{Name: "diagram-warning-stroke", Group: "diagram", Kind: "color", Light: "#b7791f", Dark: "#d29922", Doc: "Stroke of the warning style."},
	{Name: "diagram-warning-ink", Group: "diagram", Kind: "color", Light: "#805015", Dark: "#f2cc60", Doc: "Text of the warning style."},
	{Name: "diagram-boundary-fill", Group: "diagram", Kind: "color", Light: "#f0f3f6", Dark: "#161b22", Doc: "Fill of the boundary style."},
	{Name: "diagram-boundary-stroke", Group: "diagram", Kind: "color", Light: "#c3cdd8", Dark: "#30363d", Doc: "Stroke of the boundary style."},
	{Name: "diagram-title-ink", Group: "diagram", Kind: "color", Light: "#172033", Dark: "#e6edf3", Doc: "Text of the title style."},
	{Name: "diagram-shadow", Group: "diagram", Kind: "color", Light: "#0f172a", Dark: "#010409", Doc: "Colour of sticky-note shadows."},
	{Name: "diagram-yellow-sticky", Group: "diagram-palette", Kind: "color", Light: "#fff3a3", Dark: "#4d4108"},
	{Name: "diagram-yellow-tint", Group: "diagram-palette", Kind: "color", Light: "#fff8d6", Dark: "#2b2508"},
	{Name: "diagram-yellow-mark", Group: "diagram-palette", Kind: "color", Light: "#facc15", Dark: "#e3b341"},
	{Name: "diagram-yellow-accent", Group: "diagram-palette", Kind: "color", Light: "#a16207", Dark: "#e3b341"},
	{Name: "diagram-yellow-ink", Group: "diagram-palette", Kind: "color", Light: "#3f2d00", Dark: "#fff5b1"},
	{Name: "diagram-pink-sticky", Group: "diagram-palette", Kind: "color", Light: "#ffc9dc", Dark: "#5c1a37"},
	{Name: "diagram-pink-tint", Group: "diagram-palette", Kind: "color", Light: "#ffe8f0", Dark: "#2f1420"},
	{Name: "diagram-pink-mark", Group: "diagram-palette", Kind: "color", Light: "#f472b6", Dark: "#f472b6"},
	{Name: "diagram-pink-accent", Group: "diagram-palette", Kind: "color", Light: "#be185d", Dark: "#f778ba"},
	{Name: "diagram-pink-ink", Group: "diagram-palette", Kind: "color", Light: "#500724", Dark: "#ffd6e8"},
	{Name: "diagram-blue-sticky", Group: "diagram-palette", Kind: "color", Light: "#c7defe", Dark: "#15315e"},
	{Name: "diagram-blue-tint", Group: "diagram-palette", Kind: "color", Light: "#e8f1ff", Dark: "#121d2f"},
	{Name: "diagram-blue-mark", Group: "diagram-palette", Kind: "color", Light: "#60a5fa", Dark: "#58a6ff"},
	{Name: "diagram-blue-accent", Group: "diagram-palette", Kind: "color", Light: "#1d4ed8", Dark: "#58a6ff"},
	{Name: "diagram-blue-ink", Group: "diagram-palette", Kind: "color", Light: "#172554", Dark: "#cae8ff"},
	{Name: "diagram-green-sticky", Group: "diagram-palette", Kind: "color", Light: "#c6efcf", Dark: "#16402a"},
	{Name: "diagram-green-tint", Group: "diagram-palette", Kind: "color", Light: "#e7f8eb", Dark: "#12261e"},
	{Name: "diagram-green-mark", Group: "diagram-palette", Kind: "color", Light: "#4ade80", Dark: "#3fb950"},
	{Name: "diagram-green-accent", Group: "diagram-palette", Kind: "color", Light: "#15803d", Dark: "#56d364"},
	{Name: "diagram-green-ink", Group: "diagram-palette", Kind: "color", Light: "#052e16", Dark: "#d2f8d9"},
	{Name: "diagram-purple-sticky", Group: "diagram-palette", Kind: "color", Light: "#dccdfd", Dark: "#34245e"},
	{Name: "diagram-purple-tint", Group: "diagram-palette", Kind: "color", Light: "#f1ebff", Dark: "#1f1830"},
	{Name: "diagram-purple-mark", Group: "diagram-palette", Kind: "color", Light: "#a78bfa", Dark: "#a371f7"},
	{Name: "diagram-purple-accent", Group: "diagram-palette", Kind: "color", Light: "#6d28d9", Dark: "#bc8cff"},
	{Name: "diagram-purple-ink", Group: "diagram-palette", Kind: "color", Light: "#2e1065", Dark: "#eddeff"},
	{Name: "diagram-gray-sticky", Group: "diagram-palette", Kind: "color", Light: "#e2e8f0", Dark: "#2d333b"},
	{Name: "diagram-gray-tint", Group: "diagram-palette", Kind: "color", Light: "#f1f5f9", Dark: "#1c2128"},
	{Name: "diagram-gray-mark", Group: "diagram-palette", Kind: "color", Light: "#94a3b8", Dark: "#8b949e"},
	{Name: "diagram-gray-accent", Group: "diagram-palette", Kind: "color", Light: "#475569", Dark: "#9198a1"},
	{Name: "diagram-gray-ink", Group: "diagram-palette", Kind: "color", Light: "#0f172a", Dark: "#e6edf3"},
}
