package grammar

// contentCommands are the shapes that author content and run the tools
// around it: init, the design and implementation-deck writers, coverage
// repair, claims, the work plan, and the read-only commands. With the living
// record writers in commands they make the table every command the CLI runs.
var contentCommands = []Command{
	{
		Name: "add-chapter", Status: StatusImplemented, Mutates: true, Writes: []string{"chapter"},
		Usage:   "change-saga add-chapter (--feature ID | --app designsystem) [flags] <saga> <name>",
		Summary: "add one independently reviewable narrative chapter to the Saga",
		Flags: []Flag{
			optional("app", "APP", "author into the app-level design system instead of a feature: designsystem"),
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			optional("id", "ID", "stable chapter identifier"),
			optional("order", "N", "display order"),
			optional("title", "TEXT", "chapter title"),
		},
		Positionals: []string{"<saga>", "<name>"},
	},
	{
		Name: "add-claim", Status: StatusImplemented, Mutates: true, Writes: []string{"claim"},
		Usage:   "change-saga add-claim --target TARGET --kind KIND --statement TEXT --ref LOCATION [--ref LOCATION...] <saga>",
		Summary: "record one falsifiable author assertion and the code that supports it",
		Flags: []Flag{
			optional("id", "ID", "stable claim id; generated when omitted"),
			required("kind", "KIND", "behavior, invariant, performance, compatibility, security, data, ux, or test"),
			repeatable("ref", "LOCATION", "supporting code location <commit>:<path>[#L<start>[-L<end>]]; repeatable", true),
			optional("repo", "PATH", "source repository checkout; required when separate"),
			required("statement", "TEXT", "falsifiable assertion made by the change author"),
			required("target", "TARGET", "saga, chapter, section, fragment, or landmark target"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "add-fragment", Status: StatusImplemented, Mutates: true, Writes: []string{"fragment"},
		Usage:   "change-saga add-fragment (--feature ID | --app designsystem | --section TARGET) [flags] <saga>",
		Summary: "add a narrative artifact to a chapter or section",
		Flags: []Flag{
			optional("app", "APP", "author into the app-level design system instead of a feature: designsystem"),
			optional("entrypoint", "ENTRYPOINT", "entrypoint within a source directory"),
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			optional("id", "ID", "stable fragment identifier"),
			optional("media-type", "MEDIA_TYPE", "explicit media type"),
			optional("name", "NAME", "fragment directory name without .fragment"),
			optional("order", "N", "display order"),
			optional("section", "TARGET", "containing section"),
			optional("source", "PATH", "source file to copy into the fragment"),
			optional("title", "TEXT", "fragment title"),
			optional("type", "TYPE", "markdown, html, svg, image, or text"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "add-item", Status: StatusImplemented, Mutates: true, Writes: []string{"item"},
		Usage:   "change-saga add-item [--review ID] --slide TARGET --kind KIND [selector] [--record URN] [flags] <saga>",
		Summary: "add one semantic visual item, including an evidence-bearing callout overlay, and append it to the slide reading order",
		Flags: []Flag{
			optional("about", "ABOUT", "for callouts, another item id on this slide"),
			optional("body", "TEXT", "required concise callout body"),
			optional("description", "TEXT", "non-visual semantic description"),
			optional("element-id", "ELEMENT_ID", "id of an SVG or HTML element"),
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			optional("hotspot", "HOTSPOT", "optional normalized on-canvas hit area"),
			optional("id", "ID", "stable lowercase item identifier"),
			required("kind", "KIND", "node, edge, region, transition, statement, risk, metric, example, or callout"),
			optional("label", "TEXT", "concise reviewer-facing label"),
			optional("leader", "LEADER", "none, line, or arrow"),
			optional("placement", "PLACEMENT", "top, right, bottom, left, or overlay"),
			optional("rank", "RANK", "non-negative item order; defaults after the last item"),
			optional("record", "URN", "the record the item points at: required for onboarding items (a persona, feature, or story URN); optional for review items (a story, feature slide, or other record to open beside the change)"),
			optional("region", "REGION", "normalized image region x,y,width,height"),
			optional("review", "ID", "the pull request review whose slide receives the item"),
			required("slide", "TARGET", "containing slide path, id, or URN"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "add-landmark", Status: StatusImplemented, Mutates: true, Writes: []string{"landmark"},
		Usage:   "change-saga add-landmark [flags] <saga>",
		Summary: "create a coverable target for one Markdown heading, exact text span, HTML/SVG element, or normalized image region inside a fragment",
		Flags: []Flag{
			optional("description", "TEXT", "semantic explanation for AI and non-visual consumers"),
			optional("element-id", "ELEMENT_ID", "id of an HTML or SVG element; SVG bounds become an on-canvas link automatically"),
			optional("heading-id", "HEADING_ID", "explicit Markdown heading anchor; must equal --id when --id is provided"),
			optional("hotspot", "HOTSPOT", "normalized on-canvas hit area x,y,width,height; overrides inferred SVG element bounds"),
			optional("id", "ID", "stable landmark identifier"),
			optional("label", "TEXT", "reviewer-facing landmark label"),
			optional("prefix", "PREFIX", "text immediately before --text, for disambiguation"),
			optional("region", "REGION", "normalized image region x,y,width,height"),
			optional("suffix", "SUFFIX", "text immediately after --text, for disambiguation"),
			optional("target", "TARGET", "containing .fragment directory or fragment URN"),
			optional("text", "TEXT", "exact text to mark in a Markdown or text fragment"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "add-section", Status: StatusImplemented, Mutates: true, Writes: []string{"section"},
		Usage:   "change-saga add-section [flags] <saga> <section/path>",
		Summary: "group related narrative content inside a chapter",
		Flags: []Flag{
			optional("app", "APP", "author into the app-level design system instead of a feature: designsystem"),
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			optional("id", "ID", "stable section identifier"),
			optional("order", "N", "display order"),
			optional("title", "TEXT", "section title"),
		},
		Positionals: []string{"<saga>", "<section/path>"},
	},
	{
		Name: "add-slide", Status: StatusImplemented, Mutates: true, Writes: []string{"slide"},
		Usage:   "change-saga add-slide (--deck TARGET | --review ID) --intent INTENT --layout LAYOUT [flags] <saga> <name>",
		Summary: "add one visual argument to an implementation deck",
		Flags: []Flag{
			optional("deck", "TARGET", "containing deck path, id, or URN"),
			optional("entrypoint", "ENTRYPOINT", "simple filename whose extension selects the compact slide asset name"),
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			optional("exception-rationale", "EXCEPTION_RATIONALE", "required reason for a custom layout"),
			optional("id", "ID", "stable slide identifier"),
			required("intent", "INTENT", "reviewer job: orient, explain, compare, trace, prove, risk, or conclude"),
			required("layout", "LAYOUT", "canvas arrangement, not diagram meaning: hero, diagram, before-after, sequence, evidence, risk, or custom"),
			optional("media-type", "MEDIA_TYPE", "visual media type"),
			optional("rank", "RANK", "non-negative review order; defaults after the last slide"),
			optional("review", "ID", "add the slide to this pull request review's deck instead of --deck"),
			optional("section", "SECTION", "optional section label shown as a subtle divider inside the deck"),
			optional("source", "PATH", "SVG, image, or self-contained HTML source"),
			optional("takeaway", "TAKEAWAY", "single reviewer takeaway (maximum 180 characters)"),
			optional("title", "TEXT", "slide title"),
		},
		Positionals: []string{"<saga>", "<name>"},
	},
	{
		Name: "design add-chapter", Status: StatusImplemented, Mutates: true, Writes: []string{"chapter"},
		Usage:   "change-saga design add-chapter --feature ID [flags] <saga> <name>",
		Summary: "add one independently authored technical-design concern",
		Flags: []Flag{
			required("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			optional("id", "ID", "stable chapter identifier"),
			optional("order", "N", "display order"),
			optional("title", "TEXT", "chapter title"),
		},
		Positionals: []string{"<saga>", "<name>"},
	},
	{
		Name: "design add-fragment", Status: StatusImplemented, Mutates: true, Writes: []string{"fragment"},
		Usage:   "change-saga design add-fragment (--feature ID | --section TARGET) [flags] <saga>",
		Summary: "add an addressable technical-design artifact",
		Flags: []Flag{
			optional("entrypoint", "ENTRYPOINT", "entrypoint within a source directory"),
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			optional("id", "ID", "stable fragment identifier"),
			optional("media-type", "MEDIA_TYPE", "explicit media type"),
			optional("name", "NAME", "fragment directory name without .fragment"),
			optional("order", "N", "display order"),
			optional("section", "TARGET", "containing section"),
			optional("source", "PATH", "source file to copy into the fragment"),
			optional("title", "TEXT", "fragment title"),
			optional("type", "TYPE", "markdown, html, svg, image, or text"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "design add-section", Status: StatusImplemented, Mutates: true, Writes: []string{"section"},
		Usage:   "change-saga design add-section [flags] <saga> <section/path>",
		Summary: "partition a design chapter around one coherent subsystem, workflow, or decision so concurrent agents can work without contending on a shared fragment",
		Flags: []Flag{
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			optional("id", "ID", "stable section identifier"),
			optional("order", "N", "display order"),
			optional("title", "TEXT", "section title"),
		},
		Positionals: []string{"<saga>", "<section/path>"},
	},
	{
		Name: "design set-fragment-content", Status: StatusImplemented, Mutates: true, Writes: []string{"fragment"},
		Usage:   "change-saga design set-fragment-content --target TARGET --source FILE|- [--feature ID] [--json|--quiet] <saga>",
		Summary: "replace authored design content while preserving its stable target",
		Flags: []Flag{
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			{Name: "json", Description: "emit one machine-readable JSON result"},
			{Name: "quiet", Description: "suppress successful output"},
			required("source", "FILE|-", "content file, or - for standard input"),
			required("target", "TARGET", "fragment path, ID, or target URN"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "init", Status: StatusImplemented, Mutates: true, Writes: []string{"saga", "overview-pitch", "overview-description"},
		Usage:   "change-saga init [flags] <name.saga>",
		Summary: "create the app Saga: the saga.json manifest, a reviewer README, and the app overview under ___overview",
		Flags: []Flag{
			{Name: "allow-local-repository", Description: "persist a local file:// repository identity when origin is unavailable"},
			{Name: "allow-repository-mismatch", Description: "accept an explicitly declared repository that differs from origin"},
			optional("id", "ID", "stable saga identifier"),
			optional("repo", "PATH", "source repository checkout"),
			optional("repository", "REPOSITORY", "portable absolute source repository URI; defaults to origin"),
			optional("title", "TEXT", "saga title"),
		},
		Positionals: []string{"<name.saga>"},
	},
	{
		Name: "install-skill", Status: StatusImplemented,
		Usage:       "change-saga install-skill",
		Summary:     "print the agent-agnostic prompt that installs the change-saga authoring skill",
		Flags:       []Flag{},
		Positionals: []string(nil),
	},
	{
		Name: "open", Status: StatusImplemented,
		Usage:   "change-saga open [--addr ADDR] [--repo PATH] [--against REV [--head REV]] <saga>",
		Summary: "start a managed loopback reviewer, open it in a browser, and return after printing the PID and active URL",
		Flags: []Flag{
			optional("addr", "ADDR", "loopback listen address; remote serving is disabled"),
			optional("against", "REV", "compare: view what --head changes since its merge-base with this revision, the way a pull request does; omit to observe --head"),
			optional("head", "REV", "the commit to observe, or the head of the comparison"),
			{Name: "open", Description: "open the review in a browser"},
			optional("repo", "PATH", "source repository checkout; required when separate"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "plan add-contract", Status: StatusImplemented, Mutates: true, Writes: []string{"work-contract"},
		Usage:   "change-saga plan add-contract --feature ID --id ID --revision ID --kind KIND --provider URN --consumer URN --statement TEXT --acceptance TEXT... --request-id ID [flags] <saga>",
		Summary: "define the versioned interface between parallel provider and consumer work items",
		Flags: []Flag{
			repeatable("acceptance", "TEXT", "acceptance check; repeatable", true),
			required("consumer", "URN", "consumer work-item URN"),
			required("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			required("id", "ID", "stable contract id"),
			{Name: "json", Description: "emit a machine-readable result"},
			required("kind", "KIND", "deliverable, interface, handoff, or quality_gate"),
			required("provider", "URN", "provider work-item URN"),
			required("request-id", "ID", "required idempotency key"),
			required("revision", "ID", "stable initial revision id"),
			required("statement", "TEXT", "contract statement"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "plan add-dependency", Status: StatusImplemented, Mutates: true, Writes: []string{"work-dependency"},
		Usage:   "change-saga plan add-dependency --feature ID --id ID --prerequisite URN --dependent URN --condition KIND --reason TEXT --request-id ID [flags] <saga>",
		Summary: "record a real prerequisite between work items",
		Flags: []Flag{
			required("condition", "KIND", "progress_done, merge_integrated, or contract_fulfilled"),
			optional("contract-revision", "CONTRACT_REVISION", "exact contract revision for contract_fulfilled"),
			required("dependent", "URN", "dependent work-item URN"),
			required("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			required("id", "ID", "stable dependency id"),
			{Name: "json", Description: "emit a machine-readable result"},
			required("prerequisite", "URN", "prerequisite work-item URN"),
			required("reason", "TEXT", "why the dependency is necessary"),
			required("request-id", "ID", "required idempotency key"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "plan add-item", Status: StatusImplemented, Mutates: true, Writes: []string{"work-item", "work-item-revision"},
		Usage:   "change-saga plan add-item --feature ID --id ID --revision ID --title TEXT --objective TEXT --deliverable TEXT... --request-id ID [flags] <saga>",
		Summary: "add one independently assignable, mergeable unit of work and link it to the requirements and design it advances",
		Flags: []Flag{
			repeatable("completion-check", "COMPLETION_CHECK", "completion check; repeatable", false),
			repeatable("contract", "CONTRACT", "contract or contract-revision URN; repeatable", false),
			repeatable("deliverable", "TEXT", "declared deliverable; repeatable", true),
			repeatable("dependency", "DEPENDENCY", "dependency URN; repeatable", false),
			required("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			required("id", "ID", "stable work-item id"),
			{Name: "json", Description: "emit a machine-readable result"},
			repeatable("merge-unit", "MERGE_UNIT", "merge-unit JSON object; repeatable", false),
			required("objective", "TEXT", "independently assignable objective"),
			repeatable("parent", "PARENT", "current revision head URN; repeatable", false),
			repeatable("relation", "RELATION", "requirements/design relation URN; repeatable", false),
			required("request-id", "ID", "required idempotency key"),
			required("revision", "ID", "stable definition revision id"),
			required("title", "TEXT", "work-item title"),
			repeatable("touch-area", "TOUCH_AREA", "touch-area JSON object; repeatable", false),
			optional("wave", "WAVE", "current wave URN"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "plan add-wave", Status: StatusImplemented, Mutates: true, Writes: []string{"wave", "wave-revision"},
		Usage:   "change-saga plan add-wave --feature ID --id ID --revision ID --title TEXT --objective TEXT --request-id ID [flags] <saga>",
		Summary: "add one delivery phase with explicit entry and exit conditions",
		Flags: []Flag{
			repeatable("entry-condition", "ENTRY_CONDITION", "entry condition; repeatable", false),
			required("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			repeatable("exit-condition", "EXIT_CONDITION", "exit condition; repeatable", false),
			required("id", "ID", "stable wave id"),
			{Name: "json", Description: "emit a machine-readable result"},
			required("objective", "TEXT", "wave objective"),
			optional("order", "N", "display order (not a dependency)"),
			required("request-id", "ID", "required idempotency key"),
			required("revision", "ID", "stable initial revision id"),
			required("title", "TEXT", "wave title"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "plan assign", Status: StatusImplemented, Mutates: true, Writes: []string{"work-event"},
		Usage:   "change-saga plan assign --item URN --workspace UUID --repository-id ID --branch NAME --request-id ID [flags] <saga>",
		Summary: "bind a work item to a concrete workspace and branch so progress can be shown in the live Saga",
		Flags: []Flag{
			required("branch", "NAME", "workspace branch"),
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			optional("event", "ID", "stable event id; generated when omitted"),
			required("item", "URN", "canonical work-item URN"),
			{Name: "json", Description: "emit a machine-readable result"},
			optional("label", "TEXT", "optional workspace label"),
			repeatable("parent", "PARENT", "current assignment head URN; repeatable", false),
			required("repository-id", "ID", "portable repository identity"),
			required("request-id", "ID", "required idempotency key"),
			optional("role", "ROLE", "owner, contributor, or observer"),
			optional("source-branch", "SOURCE_BRANCH", "workspace source branch"),
			optional("summary", "TEXT", "assignment summary"),
			required("workspace", "UUID", "DevSwarm workspace UUID"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "plan progress", Status: StatusImplemented, Mutates: true, Writes: []string{"work-event"},
		Usage:   "change-saga plan progress --item URN --from EVENT... --to STATE --request-id ID [flags] <saga>",
		Summary: "append explicit workspace progress against the item",
		Flags: []Flag{
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			optional("event", "ID", "stable event id; generated when omitted"),
			repeatable("from", "EVENT", "current progress head event URN; repeatable for reconciliation", true),
			required("item", "URN", "canonical work-item URN"),
			{Name: "json", Description: "emit a machine-readable result"},
			optional("reason", "TEXT", "reason, required for blocked and cancelled"),
			required("request-id", "ID", "required idempotency key"),
			optional("summary", "TEXT", "progress summary"),
			required("to", "STATE", "planned, ready, in_progress, blocked, done, or cancelled"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "plan record-merge", Status: StatusImplemented, Mutates: true, Writes: []string{"work-event"},
		Usage:   "change-saga plan record-merge --item URN --unit ID --state STATE --request-id ID [flags] <saga>",
		Summary: "append merge evidence for a declared merge unit",
		Flags: []Flag{
			optional("commit", "REV", "full merge commit OID (alias for --merge-oid)"),
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			optional("event", "ID", "stable event id; generated when omitted"),
			repeatable("from", "FROM", "current merge head event URN; repeatable for reconciliation", false),
			optional("head-oid", "HEAD_OID", "full delivered head OID"),
			required("item", "URN", "canonical work-item URN"),
			{Name: "json", Description: "emit a machine-readable result"},
			optional("merge-oid", "MERGE_OID", "full integration commit OID"),
			required("request-id", "ID", "required idempotency key"),
			optional("revert-oid", "REVERT_OID", "full revert commit OID"),
			required("state", "STATE", "planned, ready, integrated, reverted, or abandoned"),
			optional("summary", "TEXT", "merge-event summary"),
			required("unit", "ID", "merge-unit id from the current work-item revision"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "plan revise-item", Status: StatusImplemented, Mutates: true, Writes: []string{"work-item-revision"},
		Usage:   "change-saga plan revise-item --item URN --revision ID --parent URN... --title TEXT --objective TEXT --deliverable TEXT... --request-id ID [flags] <saga>",
		Summary: "append a complete work-item revision when scope, touch areas, deliverables, or merge units change",
		Flags: []Flag{
			repeatable("completion-check", "COMPLETION_CHECK", "completion check; repeatable", false),
			repeatable("contract", "CONTRACT", "contract or contract-revision URN; repeatable", false),
			repeatable("deliverable", "TEXT", "declared deliverable; repeatable", true),
			repeatable("dependency", "DEPENDENCY", "dependency URN; repeatable", false),
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			required("item", "URN", "canonical work-item URN"),
			{Name: "json", Description: "emit a machine-readable result"},
			repeatable("merge-unit", "MERGE_UNIT", "merge-unit JSON object; repeatable", false),
			required("objective", "TEXT", "independently assignable objective"),
			repeatable("parent", "URN", "current revision head URN; repeatable", true),
			repeatable("relation", "RELATION", "requirements/design relation URN; repeatable", false),
			required("request-id", "ID", "required idempotency key"),
			required("revision", "ID", "stable definition revision id"),
			required("title", "TEXT", "work-item title"),
			repeatable("touch-area", "TOUCH_AREA", "touch-area JSON object; repeatable", false),
			optional("wave", "WAVE", "current wave URN"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "plan revise-wave", Status: StatusImplemented, Mutates: true, Writes: []string{"wave-revision"},
		Usage:   "change-saga plan revise-wave --wave URN --revision ID --parent URN... --title TEXT --objective TEXT --request-id ID [flags] <saga>",
		Summary: "append a complete wave revision as sequencing or convergence changes",
		Flags: []Flag{
			repeatable("entry-condition", "ENTRY_CONDITION", "complete entry condition; repeatable", false),
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			repeatable("exit-condition", "EXIT_CONDITION", "complete exit condition; repeatable", false),
			{Name: "json", Description: "emit a machine-readable result"},
			required("objective", "TEXT", "complete revised objective"),
			optional("order", "N", "complete revised display order"),
			repeatable("parent", "URN", "current revision head URN; repeatable", true),
			required("request-id", "ID", "required idempotency key"),
			required("revision", "ID", "stable revision id"),
			required("title", "TEXT", "complete revised title"),
			required("wave", "URN", "canonical wave URN"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "prototype add-external", Status: StatusImplemented, Mutates: true, Writes: []string{"prototype", "prototype-revision"},
		Usage:   "change-saga prototype add-external --feature ID --id ID --revision ID --title TEXT --url URL [--embed-url URL --provider ID --embed-origin ORIGIN] [flags] <saga>",
		Summary: "add a prototype that lives outside the Saga",
		Flags: []Flag{
			optional("embed-origin", "ORIGIN", "allowlisted embed origin; must equal the --embed-url origin"),
			optional("embed-url", "URL", "explicitly allowed https embed URL"),
			required("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			optional("fallback-url", "FALLBACK_URL", "link shown when the embed cannot render; defaults to --url"),
			required("id", "ID", "stable prototype id"),
			{Name: "json", Description: "emit a machine-readable result"},
			repeatable("permission", "PERMISSION", "allowed iframe permission token; repeatable", false),
			optional("provider", "ID", "allowlisted embed provider id"),
			optional("request-id", "REQUEST_ID", "idempotency key"),
			required("revision", "ID", "stable initial revision id"),
			repeatable("sandbox", "SANDBOX", "allowed iframe sandbox token; repeatable", false),
			optional("state", "STATE", "draft, ready, or retired"),
			required("title", "TEXT", "prototype title"),
			required("url", "URL", "canonical external prototype URL"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "prototype revise", Status: StatusImplemented, Mutates: true, Writes: []string{"prototype-revision"},
		Usage:   "change-saga prototype revise --prototype URN --revision ID --parent URN... --title TEXT (--source PATH | --url URL) [flags] <saga>",
		Summary: "append a complete immutable prototype revision",
		Flags: []Flag{
			optional("embed-origin", "EMBED_ORIGIN", "allowlisted embed origin; must equal the --embed-url origin"),
			optional("embed-url", "EMBED_URL", "explicitly allowed https embed URL"),
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			optional("fallback-url", "FALLBACK_URL", "link shown when the embed cannot render; defaults to --url"),
			{Name: "json", Description: "emit a machine-readable result"},
			repeatable("parent", "URN", "current revision head URN; repeatable", true),
			repeatable("permission", "PERMISSION", "allowed iframe permission token; repeatable", false),
			required("prototype", "URN", "canonical prototype URN"),
			optional("provider", "PROVIDER", "allowlisted embed provider id"),
			optional("request-id", "REQUEST_ID", "idempotency key"),
			required("revision", "ID", "stable revision id"),
			repeatable("sandbox", "SANDBOX", "allowed iframe sandbox token; repeatable", false),
			optional("source", "PATH", "fresh .html file or real directory for an html revision"),
			optional("state", "STATE", "draft, ready, or retired"),
			required("title", "TEXT", "complete revised title"),
			optional("url", "URL", "canonical external prototype URL"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "query", Status: StatusImplemented,
		Usage:   "change-saga query <operation> --saga PATH [--repo PATH] [operation flags]",
		Summary: "run one read-only query and write exactly one JSON value; change-saga query schema OPERATION describes each operation's flags and result",
		Flags: []Flag{
			required("saga", "PATH", "the Saga to read"), optional("repo", "PATH", "source repository checkout; required when separate"), againstFlag, headFlag,
		},
		Positionals: []string{"<operation>"},
	},
	{
		Name: "remove-coverage", Status: StatusImplemented, Mutates: true, Writes: []string{"code-evidence"},
		Usage:   "change-saga remove-coverage --record PATH [--dry-run] [--json|--quiet] <saga>",
		Summary: "delete one exact coverage record named by query mappings or fragment-diffs",
		Flags: []Flag{
			{Name: "dry-run", Description: "validate and report the deletion without writing"},
			{Name: "json", Description: "emit one machine-readable result"},
			{Name: "quiet", Description: "suppress successful output"},
			required("record", "PATH", "evidence_file returned by query mappings or fragment-diffs"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "replace-coverage", Status: StatusImplemented, Mutates: true, Writes: []string{"code-evidence"},
		Usage:   "change-saga replace-coverage --record PATH [coverage flags] [--batch FILE|-] [--dry-run] [--against REV [--head REV]] <saga>",
		Summary: "atomically replace one coverage record with one or more newly resolved records",
		Flags: []Flag{
			optional("against", "REV", "compare: view what --head changes since its merge-base with this revision, the way a pull request does; omit to observe --head"),
			{Name: "allow-repository-mismatch", Description: "use a checkout whose origin differs from the declared repository"},
			optional("batch", "FILE|-", "read coverage records from a JSON file, or - for stdin"),
			{Name: "changed-lines", Description: "reference every changed line of --path, and the whole file for file events; optionally one --side"},
			optional("commit", "REV", "pin at this revision instead of a comparison side"),
			{Name: "dry-run", Description: "resolve and report the coverage records without writing them"},
			{Name: "file", Description: "reference the whole file at --path: renames, mode and binary changes, and whole added or deleted files"},
			optional("head", "REV", "the commit to observe, or the head of the comparison"),
			{Name: "json", Description: "emit one machine-readable summary instead of every reference"},
			optional("lines", "LINES", "line ranges on that side, for example 4-9,12"),
			optional("name", "NAME", "coverage filename without .json"),
			optional("note", "NOTE", "optional explanation for report authors"),
			optional("path", "PATH", "repository path"),
			{Name: "quiet", Description: "suppress successful output"},
			required("record", "PATH", "evidence_file returned by query mappings or fragment-diffs"),
			repeatable("ref", "REF", "code location <commit>:<path>[#L<start>[-L<end>]]; repeatable", false),
			optional("repo", "PATH", "source repository checkout; required when separate"),
			optional("side", "SIDE", "comparison side: new (the head commit) or old (the merge-base, for deleted code)"),
			optional("target", "TARGET", "section, .fragment, landmark, or Item receiving evidence; accepts <fragment>#<landmark-id>"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "serve", Status: StatusImplemented,
		Usage:   "change-saga serve [--addr ADDR] [--repo PATH] [--open] [--detach] [--against REV [--head REV]] <saga>",
		Summary: "serve the saga on loopback for review",
		Flags: []Flag{
			optional("addr", "ADDR", "loopback listen address; remote serving is disabled"),
			optional("against", "REV", "compare: view what --head changes since its merge-base with this revision, the way a pull request does; omit to observe --head"),
			{Name: "detach", Description: "run in the background and return the PID and active URL"},
			optional("head", "REV", "the commit to observe, or the head of the comparison"),
			{Name: "open", Description: "open the review in a browser"},
			optional("repo", "PATH", "source repository checkout; required when separate"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "set-fragment-content", Status: StatusImplemented, Mutates: true, Writes: []string{"fragment"},
		Usage:   "change-saga set-fragment-content --target TARGET --source FILE|- [--json|--quiet] <saga>",
		Summary: "replace a fragment entrypoint through the supported authoring API",
		Flags: []Flag{
			optional("app", "APP", "author into the app-level design system instead of a feature: designsystem"),
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			{Name: "json", Description: "emit one machine-readable JSON result"},
			{Name: "quiet", Description: "suppress successful output"},
			required("source", "FILE|-", "content file, or - for standard input"),
			required("target", "TARGET", "fragment path, ID, or target URN"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "set-slide-content", Status: StatusImplemented, Mutates: true, Writes: []string{"slide"},
		Usage:   "change-saga set-slide-content [--review ID] --target TARGET --source FILE|- [--json|--quiet] <saga>",
		Summary: "replace a slide's visual entrypoint while preserving its stable target and items",
		Flags: []Flag{
			optional("feature", "ID", "feature id or URN; when creating feature content it defaults to the app's only feature (or a first feature named after the branch), otherwise it must name the feature that holds the record"),
			{Name: "json", Description: "emit one machine-readable JSON result"},
			{Name: "quiet", Description: "suppress successful output"},
			optional("review", "ID", "the pull request review whose slide is replaced"),
			required("source", "FILE|-", "content file, or - for standard input"),
			required("target", "TARGET", "slide path, id, or target URN"),
		},
		Positionals: []string{"<saga>"},
	},
	{
		Name: "verify-claim", Status: StatusImplemented, Mutates: true, Writes: []string{"verification"},
		Usage:   "change-saga verify-claim --claim ID --status STATUS --summary TEXT [flags] <saga>",
		Summary: "append an independent verification result without rewriting the claim or prior results",
		Flags: []Flag{
			required("claim", "ID", "claim id being evaluated"),
			optional("command", "COMMAND", "reproducible command used during verification"),
			optional("id", "ID", "stable verification id; generated when omitted"),
			optional("method", "METHOD", "test, command, measurement, inspection, or analysis"),
			required("status", "STATUS", "unverified, verified, failed, or inconclusive"),
			required("summary", "TEXT", "what was or was not established"),
		},
		Positionals: []string{"<saga>"},
	},
}

func init() { commands = append(commands, contentCommands...) }
